### ISSUE TITLE
Unable to create new ledger accounts

### ISSUE THREAD

**Issue by Beakerboy** [mstenta/ledger#2]
/ledger/account/add?ledger_account_type=asset
 receive the following error:
"You are not authorized to access this page."

**Comment by mstenta** [comment]
Hmm yea I am seeing that too. Also, noticing that the "Add Ledger Account" button links to "/admin/structure/ledger_account/add", rather than "/ledger/account/add".

Ultimately, it should be:

* `/ledger/account/add` - Lists the types of accounts that can be added
* `/ledger/account/add/[type]` - The form for adding a new account of a specific type.

This will be consistent with the way node does it. Ie: `/node/add/page`

**Comment by mstenta** [comment]
I'm starting a 3.x branch from scratch for Drupal 9. This shouldn't be an issue anymore. :-)
